#include "core/bot/bot_installation_assembler.hpp"
#include "onebot11/bot/operations.hpp"
#include "support/bot_platform_fixture.hpp"
#include "telegram/bot/operations.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <fstream>
#include <set>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace {

using namespace obcx::bot;
using namespace obcx::onebot11::bot;
using namespace obcx::telegram::bot;

// This is frozen input, not generated by the codecs being tested.
auto baseline() -> const Json & {
  static const auto document = [] {
    std::ifstream input{OBCX_BOT_GOLDEN_PATH};
    if (!input) {
      throw std::runtime_error("cannot open bot contract golden fixture");
    }
    return Json::parse(input);
  }();
  return document;
}

template <typename Request, typename Result>
void replay(const std::string_view action) {
  SCOPED_TRACE(action);
  const auto &fixture = baseline().at("operations").at(std::string{action});
  const auto request = fixture.at("request").get<Request>();
  request.validate();
  EXPECT_EQ(Json(request).dump(), fixture.at("request").dump());
  const auto success = fixture.at("success").get<BotOperationResult<Result>>();
  ASSERT_TRUE(success.ok());
  success.value->validate();
  EXPECT_EQ(Json(success).dump(), fixture.at("success").dump());
  for (const auto &error : baseline().at("errors")) {
    const auto failure = error.get<BotOperationResult<Result>>();
    ASSERT_FALSE(failure.ok());
    EXPECT_EQ(Json(failure).dump(), error.dump());
  }
}

TEST(BotOperationGoldenTest, CommonMessaging) {
  replay<SendGroupMessageRequest, SendMessageResult>("message.send_group");
  replay<DeleteMessageRequest, DeleteMessageResult>("message.delete");
}

TEST(BotOperationGoldenTest, TelegramMessagingAndMedia) {
  replay<SendTelegramTopicMessageRequest, SendMessageResult>(
      "telegram.message.send_topic");
  replay<EditTelegramMessageTextRequest, EditMessageTextResult>(
      "telegram.message.edit_text");
  replay<SendTelegramPhotoRequest, SendMessageResult>(
      "telegram.media.send_photo");
  replay<SendTelegramMediaGroupUrlsRequest, SendMessageResult>(
      "telegram.media.send_group_urls");
  replay<SendTelegramMediaGroupUploadsRequest, SendMessageResult>(
      "telegram.media.send_group_uploads");
  replay<FetchTelegramFileRequest, FetchedTelegramFile>(
      "telegram.media.fetch_file");
}

TEST(BotOperationGoldenTest, OneBotLookupsAndPoke) {
  replay<GetOneBotGroupMemberRequest, OneBotGroupMember>(
      "onebot11.group_member.get");
  replay<GetOneBotForwardMessageRequest, OneBotForwardMessage>(
      "onebot11.forward_message.get");
  replay<ResolveOneBotGroupFileRequest, ResolvedOneBotGroupFile>(
      "onebot11.group_file.resolve");
  replay<ResolveOneBotPrivateFileRequest, ResolvedOneBotPrivateFile>(
      "onebot11.private_file.resolve");
  replay<PokeOneBotGroupRequest, OneBotGroupPokeResult>("onebot11.group.poke");
}

TEST(BotOperationGoldenTest, ProductionRecipeManifests) {
  std::set<std::string> surfaces;
  std::set<std::string> union_actions;
  ASSERT_EQ(baseline().at("recipes").size(), 3U);
  for (const auto &fixture : baseline().at("recipes")) {
    const auto plan = obcx::test::installation_plan(
        fixture.at("surface").get<obcx::bot::SurfaceId>(),
        fixture.at("transport").get<std::string>(), "fixture", true);
    // Parsing/description do not construct transports or start providers.
    const auto recipe = obcx::core::BotInstallationAssembler::describe(*plan);
    EXPECT_EQ(recipe.recipe_id, fixture.at("id").get<std::string>());
    std::vector<std::string> actions;
    for (const auto action : recipe.advertised_actions) {
      actions.emplace_back(action.value());
    }
    std::ranges::sort(actions);
    EXPECT_EQ(Json(actions), fixture.at("actions"));
    union_actions.insert(actions.begin(), actions.end());
    surfaces.insert(fixture.at("surface").get<std::string>());
  }
  EXPECT_EQ(Json(surfaces), baseline().at("surfaces"));
  EXPECT_EQ(union_actions.size(), 13U);
  EXPECT_EQ(baseline().at("operations").size(), union_actions.size());
  for (const auto &action : union_actions) {
    EXPECT_TRUE(baseline().at("operations").contains(action));
  }
  auto no_upload = baseline()
                       .at("recipes")
                       .at(2)
                       .at("actions")
                       .get<std::vector<std::string>>();
  std::erase(no_upload, "telegram.media.send_group_uploads");
  EXPECT_EQ(Json(no_upload), baseline().at("telegram_without_uploader"));
}

} // namespace
